name: Main Testing

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  
permissions:
  contents: write

jobs:
  testing123:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run testing script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python scripts/main.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/individual_queues/*.csv  # Adds all CSV files in the directory
        git add data/agg_county_data.geojson
        git add data/all_queued_projects.json
        git add scripts/script_data/download_settings.csv
        git diff --cached --exit-code || git commit -m "Update multiple files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
